### ISSUE TITLE
Quality of resized images

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_images#10]
Just to make sure the quality of resized images is good enough.
See for instance the artefacts in this thumbnail: http://c2corgv6-images.demo-camptocamp.com/active/1474374902_2051852365MI.jpg
The BI version is not very good either compared to the original image.

**Comment by arnaud-morvan** [comment]
I've found that jpegoptim produce these artifact, I don't get artifacts with ImageMajic convert -quality option. For the same quality option, image is few larger but really better. Only one threatment with convert with quality option. This seems really better.

**Comment by asaunier** [comment]
Quality of squared thumbnails (SI images) looks poor. For instance
![1478817982_484301537si](https://cloud.githubusercontent.com/assets/1192331/20197684/0ceb25fc-a7a1-11e6-89fb-245142045bbb.jpg)

**Comment by arnaud-morvan** [comment]
This image is 120 * 120, image backend produce 200*200 squared images. Where does this image come from, where is the original image ?
Better put the link to the image on the demo.

**Comment by asaunier** [comment]
I have probably observed this behaviour on my dev instance. I will try to reproduce.

**Comment by arnaud-morvan** [comment]
What image backend is in use on your dev instance ??? probably not up to date.
Do not try to reproduce on your dev instance, better try it on the demo server.

**Comment by asaunier** [comment]
I have not been able to test on http://www.demov6.camptocamp.org/ because of https://github.com/c2corg/v6_ui/issues/894

I have then tested to upload 4 images on http://c2corgv6.demo-camptocamp.com/routes/814691/fr/calanques-les-goudes-rocher-saint-michel-d-eau-douce-le-pin-rassis

The quality of the generated thumbnails is indeed poor. But as for https://github.com/c2corg/v6_images/issues/5#issuecomment-260405724 I suspect the backend (``c2corgv6-images.demo-camptocamp.com``) is not up-to-date (120x120 images instead of 200x200).

**Comment by arnaud-morvan** [comment]
If everything goes fine on demo server, I close this
