### ISSUE TITLE
images in S3 bucket have wrong content-type set

### ISSUE THREAD

**Issue by mfournier** [c2corg/v6_images#28]
So browsers will popup the download box rather than displaying them.

```
$ curl -I  https://sos.exo.io/c2corg_active/1427576045_1944632745.jpg
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Wed, 30 Nov 2016 15:10:22 GMT
Content-Type: application/binary
Content-Length: 285164
Connection: keep-alive
ETag: "0f3290a3d030a2234be77839656e3efb"
Last-Modified: Thu, 17 Nov 2016 12:21:23 GMT
x-amz-id-2: 343996be-8cf3-4e9e-8f2d-3b0910dc9d3c
x-amz-request-id: 343996be-8cf3-4e9e-8f2d-3b0910dc9d3c
```

**Comment by asaunier** [comment]
Related to https://github.com/c2corg/v6_ui/issues/980

**Comment by asaunier** [comment]
It happens only when directly calling the image in the browser. It works when the image is embedded in a web page with an ``<img>`` tag.
Really blocking then?

**Comment by mfournier** [comment]
I wouldn't assume this to be true for all browsers, and it will definetely cause trouble for non-browser clients (search engine indexers for instance).

But yes, if this has been tested with the set of target browsers, we remove the blocker flag.

**Comment by mfournier** [comment]
@arnaud-morvan I noticed https://github.com/c2corg/v6_images/issues/29 has been merged. Have all images in the S3 bucket been updated ?
