### ISSUE TITLE
Recreating the resized images when migrating from v5 to v6

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_images#6]
When migration the images from v5 to v6, we have 2 options:
- copy-pasting all files (original images + resized ones)
- copy-pasting only the original ones and regenerating the resized ones.

The second option is probably more convenient because:
- we can choose to have resized images with different sizes (and even have more resized formats)
- we can make sure the resized images have a better quality (using a better resizing/compressing tool)
- we can change the format of the thumbnail (in v5 they are square)
- perhaps it's faster to regenerate the resized images than to rsync them from a server to another?!

**Comment by asaunier** [comment]
Perhaps a good opportunity to use bigger dimensions for the resized images?

**Comment by asaunier** [comment]
Anyway we have to make sure that no longer used resized images are not migrated to v6. See https://github.com/c2corg/v6_images/issues/11

**Comment by asaunier** [comment]
SI images should be regenerated in 150x150 instead of 120x120 (see https://github.com/c2corg/v6_ui/issues/670#issuecomment-251594763)

BI images (max 800px in v5) are too small for today's standards, It's a bit a pity to display such small images in our full-width slideshow.

**Comment by asaunier** [comment]
Resized images dimensions have been discussed in https://github.com/c2corg/v6_images/issues/5

There are many approaches because the same image may be displayed at various sizes depending on the page and of other elements: slideshow, image detail view page, image cards, images in feed cards, thumbnails in carousel, images embedded in articles etc.

There are several unfinished parts that may impact what image version is used and in what size. For instance:
* images in feed, see https://github.com/c2corg/v6_ui/issues/754
* images in articles (or other documents), embedded with a ``[img]`` tag, see https://github.com/c2corg/v6_ui/issues/712

It's probably acceptable to use images a bit bigger than needed in order to make them fit in a card (especially in feed cards if there are several images to display). Or in pages that are not loaded very often (eg. the image detail view pages?).

In addition it's better to have fewer resized versions first and to add some in the future if needed.

I would then start with the following proposal for resized versions:
* BI: max 1500px => used for slideshow and detail view pages (will most likely be shrunk in detail view pages)
* MI: max 400px => used for embedded images and bigger image in cards
* SI: 200px (square or not, I don't know) => for carousel thumbnails and smaller images in cards?

Does it make sense?

**Comment by fjacon** [comment]
OK for me.

**Comment by arnaud-morvan** [comment]
When you say BI: max 1500px, do you meen: 
- max-width: 1500px
- max-height: 1500px

**Comment by asaunier** [comment]
Yes: I meant that the biggest dimension (height or width) is 1500px (or less if the original image is smaller).

We could set a different max size for portrait (vertical) or landscape (horizontal) images because most computer screens are landscape but on the other hand there are more and more portrait devices such as phones or tablets. So it's probably simpler to use the same max size both for width and height.

**Comment by ginold** [comment]
the proposed dimensions are fine for me. Maybe there is a big gap between the MI and BI but I can't think of a page where we would need exactly 800px for ex. 

400px for MI is plenty if we want to use it in the carousel and cards, it's event a little to big but it's maybe better, because the images in the cards tend to fill the space of the card and sometimes have to be zoomed in. And so we won't need a Card Image. MI can be pretty universal.

**Comment by asaunier** [comment]
> MI can be pretty universal.

That's my opinion. They can be use in many places: various cards (including feed), embedded in articles.
And having them a bit bigger than needed could help fitting the cards whatever the orientation of the image (portrait/landscape) - cropping them a bit if needed.

Would you suggest to use them in the carousels as well? No need for SI (small square thumbnails)?
If we need them, square or not square?

> Maybe there is a big gap between the MI and BI but I can't think of a page where we would need exactly 800px for ex.

There are the image detail views. but most of the time images are loaded in the slideshows anyway. And if you open the detail views clicking on the info button in the slideshow, the BI image will already be in the browser cache. Of course not when loading from the image cards but that's not that often (except from the homepage feed?).

In the image detail views, instead of a fixed size image, could we make the image bigger or smaller depending on the space available in the screen?

**Comment by arnaud-morvan** [comment]
Done some weeks ago
