### ISSUE TITLE
v5 > v6 migration script for images

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_images#7]
- [x] Copy the (original only?) images from v5 server to v6 server.
- [x] Recreate the resized versions from the original images. See https://github.com/c2corg/v6_images/issues/6
- [ ] Make sure that the original images width and height are available in the images database, if not, compute them

See also https://github.com/c2corg/v6_api/issues/167#issuecomment-199838562

**Comment by asaunier** [comment]
@fjacon This issue has not been addressed at all I think whereas it's a critical one!

**Comment by fjacon** [comment]
OK @arnaud-morvan will work on it

**Comment by arnaud-morvan** [comment]
Concerning width and height, it is really complicated to calculate this during migration.
If I correctly understand history, it make no sense to calculate original image width and height to solve a problem with thumbnails display. See https://github.com/c2corg/v6_ui/pull/549#issuecomment-237802834

**Comment by arnaud-morvan** [comment]
@ginold : can you explain why you need original image size ?

**Comment by arnaud-morvan** [comment]
why do you not use css property max-width: 100% ?

**Comment by ginold** [comment]
One of the reasons would be to enable animations transitions between thumnail and the opening gallery, the plugin we're using needs them

 ```
       item = { // create slide object
          html: '<div class="photoswipe-image-container">' +
                      info.html() + imgHtml +
                    '</div>'
         // TODO: for zoom in animation -> add this when WIDTH & HEIGHT will be returned by API in image properties
         // w: image.naturalWidth,
         // h: image.naturalHeight
        };

        // <img> thumbnail element, retrieving thumbnail url (small img)
        if (linkEl.children.length > 0) {
         // ADD  item.src = linkEl.getAttribute('href'); when WIDHT & HEIGHT will be returned
          item.msrc = linkEl.children[0].getAttribute('src');
        }
```

The other was some CSS glitches, but i've changed something and it might be better, but still difficult to verify when i have no images available.

**Comment by arnaud-morvan** [comment]
this should do the trick : 
```
img {
  display: block;
  max-width:230px;
  max-height:95px;
  width: auto;
  height: auto;
}
```

**Comment by arnaud-morvan** [comment]
If you're displaying a thumbnail, original image size won't help you, do you really display original image ?

**Comment by ginold** [comment]
i don't _really need_, it's a nice to have info for the animations. I tried to calculate it on the client side, but the function always came too late before downloading the bigger image and showed the image with 0 dimensions.

**Comment by arnaud-morvan** [comment]
Done some weeks ago
