### ISSUE TITLE
Add a vhost for the images backend on demo server

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_images#9]
For now we use http://c2corgv6-demo.gis.internal:8480 as public url for the images backend on the demo server.
But the images are directly uploaded on backend by the browser, so we need a public url (public host name and port 80).
And there is no specific vhost present in ``/etc/apache2/sites-available`` for the images backend, so we should add one.

**Comment by arnaud-morvan** [comment]
@mfournier : Can you add a vhost for the images backend

**Comment by mfournier** [comment]
Proxy configured and details sent by email.
